name: CI - Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: emilgruzalski/gh-reusable-workflows/.github/workflows/ci-go.yml@ceb91c3420001c52c32b171e4eb1c75bfd7a523b # v1.1.0
    with:
      image-name: 'zguba-gov'
      go-version-file: 'go.mod'
      working-directory: '.'
      dockerfile: './Dockerfile'
      context: '.'
      push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
      packages: write
      security-events: write
      id-token: write